### ISSUE TITLE
Errors on install

### ISSUE THREAD

**Issue by madebymats** [jploch/FieldtypePageGrid#1] opened 2023-01-19 06:58 UTC
Installed on latest ProcessWire 3.0.210 (dev) on MAMP got the following errors.

Error installing module - FieldtypePageGrid
Modules: Unable to install module (FieldtypePageGrid): Can’t save page 0: /pg-items/: It has no parent assigned

Refreshed modules and got this:

Modules: Module reported error during install (FieldtypePageGrid): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'pg_container' for key 'name'
Module Install - FieldtypePageGrid [+16]
Modules: Module reported error during install (FieldtypePageGrid): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'pg_container' for key 'name'

**Comment by jploch** [comment] 2023-01-19 07:27
Sorry for that. I had to change the folder name from PageGrid to FieldtypePageGrid in order to make the ProcessWire module directory recognize the module. This might be related. So make sure to uninstall the old module and download a fresh copy.

**Comment by madebymats** [comment] 2023-01-27 10:18
I still get errors on install. When i try to edit the homepage i also get the following error:

`ProcessWire: ProcessPageEdit: Can’t save page 0: /pg-1/: It has no parent assigned`

**Comment by jploch** [comment] 2023-01-27 10:52
Thanks for reporting back! 
Installing the module works for me.

> Modules: Module reported error during install (FieldtypePageGrid): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'pg_container' for key 'name'

Before installing make sure there are no templates with the name "pg_container" (this template gets created when you intall the module). Also make sure to delete the pages "PageGrid items" and "PageGrid Classes" under admin in the page tree if you installed PAGEGRID before.

If that is not helping, please try to install the module on a fresh ProcessWire installation.

**Comment by jploch** [comment] 2023-01-29 12:47
Sorry for the trouble. I was able to reproduce the error (installation was working locally but not on my production server). This should now be fixed. Please update the module to version 0.0.97

Please post if this fixes you issue.

**Comment by jploch** [comment] 2023-02-01 12:45
I am closing this because the error is fixed now. Please open another issue when you are still facing problems.

**Closed as completed** 2023-02-01 12:46 UTC
